/**
 * Page extensions that render as full pages (not endpoints).
 */
const PAGE_RENDER_EXTENSIONS = ['astro', 'md', 'mdx', 'html'] as const;

/**
 * Supported page file extensions in Astro.
 * @see https://docs.astro.build/en/basics/astro-pages/#supported-page-files
 */
const PAGE_EXTENSIONS = [...PAGE_RENDER_EXTENSIONS, 'js', 'ts'] as const;

/**
 * Regular expression to match placeholders in HTML.
 */
export const PLACEHOLDER_REGEX = /__ACPS_([^_]+)__/g;

/**
 * Suffix for index routes in Astro.
 */
export const INDEX_SUFFIX = '/index';

/**
 * Auto-generated file marker.
 */
export const GENERATED_FILE_MARKER =
  '// Auto-generated by astro-cloudflare-pages-static';

/**
 * Glob pattern for all supported page files.
 */
export const PAGE_FILES_GLOB = `**/*.{${PAGE_EXTENSIONS.join(',')}}`;

/**
 * Regular expression to match all supported page file extensions.
 */
export const PAGE_FILES_REGEX = new RegExp(
  `\\.(${PAGE_EXTENSIONS.join('|')})$`
);

/**
 * Regular expression to match page render file extensions (excludes endpoints).
 */
export const PAGE_RENDER_FILES_REGEX = new RegExp(
  `\\.(${PAGE_RENDER_EXTENSIONS.join('|')})$`
);

/**
 * Creates a placeholder string for a given parameter name.
 */
export function createPlaceholder(paramName: string): string {
  return `__ACPS_${paramName}__`;
}

/**
 * Escapes HTML special characters to prevent XSS attacks.
 * Re-exported from worker/escape.js for consistency.
 */
export { escapeHtml } from './worker/escape.js';
